file = open("session9poem.txt","w")
file.write(" \nTwo roads diverged in a yellow wood,\n")
file.write("And sorry I could not travel both And be one traveler,\n")
file.write("long I stood And looked down one as far as I could\n")
file.write("To where it bent in the undergrowth;\n")
file.write("Anarga Nair ")
file.close()
